#!/usr/bin/env bash
# This file is auto-generated by Emacs via `(org-babel-tangle-file ""configuration.org"")'.

set -euxo pipefail

brew install html-tidy5

curl -L https://github.com/rust-analyzer/rust-analyzer/releases/latest/download/rust-analyzer-mac \
     -o /usr/local/bin/rust-analyzer \
  && chmod +x /usr/local/bin/rust-analyzer

rustup component add rustfmt rust-src rust-docs clippy

wget https://github.com/clojure-lsp/clojure-lsp/releases/latest/download/clojure-lsp-native-macos-amd64.zip
unzip clojure-lsp-native-macos-amd64.zip
mv clojure-lsp /usr/local/bin
rm -rf clojure-lsp-native-macos-amd64.zip

sudo npm i -g \
     typescript-language-server \
     typescript \

npm i -g pyright

brew install llvm

python3 -m pip install mypy flake8 pylint black
