#!/usr/bin/env bash

# This file is auto-generated by Emacs via `(org-babel-tangle-file "configuration.org")'.

set -euxo pipefail

rustup component add rustfmt

python3 -m pip install mypy flake8 pylint black
